version: '3.8'

services:
  backend:
    build: 
      context: ./flask
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    restart: always

  frontend:
    build: 
      context: ./html
    ports:
      - "8080:80"
    restart: always